import openpi.models.pi0_config as pi0_config
from openpi.models.vlm2_vla_config import VLM2VLAConfig
import openpi.training.optimizer as _optimizer
from openpi.training.data_config import AssetsConfig, DataConfig, LeRobotB1KDataConfig
from openpi.training.train_config import TrainConfig
import openpi.training.weight_loaders as weight_loaders


_PRETRAIN_CONFIGS = [
    TrainConfig(
        name="pi05_b1k-base",
        exp_name="openpi",
        project_name="B1K",
        model=pi0_config.Pi0Config(pi05=True, action_horizon=32),
        data=LeRobotB1KDataConfig(
            repo_id="behavior-1k/2025-challenge-demos",
            base_config=DataConfig(
                prompt_from_task=True,
                episodes_index=list(range(200)),
                behavior_dataset_root="../DATASETS/behavior/2025-challenge-demos",
                tasks=["turning_on_radio"],
                fine_grained_level=0,
            ),
        ),
        weight_loader=weight_loaders.CheckpointWeightLoader("gs://openpi-assets/checkpoints/pi05_base/params"),
        num_train_steps=30_000,
        lr_schedule=_optimizer.CosineDecaySchedule(
            peak_lr=2.5e-5,
            decay_steps=30_000,
        ),
        freeze_filter=pi0_config.Pi0Config(pi05=True, action_horizon=32).get_freeze_filter(),
        ema_decay=None,
        checkpoint_base_dir="checkpoints",
        num_workers=8,
        batch_size=8 * 32,
    ),
    TrainConfig(
        name="pi05_b1k-turning_on_radio_cs32_bs32_lr2.5e-5_step30k",
        exp_name="openpi",
        project_name="B1K",
        model=pi0_config.Pi0Config(pi05=True, action_horizon=32),
        data=LeRobotB1KDataConfig(
            repo_id="behavior-1k/2025-challenge-demos",
            base_config=DataConfig(
                prompt_from_task=True,
                episodes_index=list(range(200)),
                behavior_dataset_root="/mnt/bn/robot-mllm-data-lf-3/mlx/users/chenjunting/data/2025-challenge-demos/",
                tasks=["turning_on_radio"],
                fine_grained_level=0,
            ),
        ),
        weight_loader=weight_loaders.CheckpointWeightLoader("checkpoints/pi05-b1kpt50-cs32/params"),
        num_train_steps=30_000,
        lr_schedule=_optimizer.CosineDecaySchedule(
            peak_lr=2.5e-5,
            decay_steps=30_000,
        ),
        freeze_filter=pi0_config.Pi0Config(pi05=True, action_horizon=32).get_freeze_filter(),
        ema_decay=None,
        checkpoint_base_dir="checkpoints",
        num_workers=8,
        batch_size=8 * 32,
    ),
    TrainConfig(
        name="pi05_b1k-pt12_cs32_bs64_lr2.5e-5_step50k",
        exp_name="openpi",
        project_name="B1K",
        model=pi0_config.Pi0Config(pi05=True, action_horizon=32),
        data=LeRobotB1KDataConfig(
            repo_id="behavior-1k/2025-challenge-demos",
            base_config=DataConfig(
                prompt_from_task=True,
                episodes_index=list(range(200)),
                behavior_dataset_root="../DATASETS/behavior/2025-challenge-demos",
                tasks=[
                    "turning_on_radio",
                    "picking_up_trash",
                    "hiding_Easter_eggs",
                    "wash_a_baseball_cap",
                    "hanging_pictures",
                    "attach_a_camera_to_a_tripod",
                    "make_microwave_popcorn",
                    "bringing_water",
                    "tidying_bedroom",
                    "putting_shoes_on_rack",
                    "setting_the_fire",
                    "cook_hot_dogs",
                ],
                fine_grained_level=0,
            ),
        ),
        weight_loader=weight_loaders.CheckpointWeightLoader("gs://openpi-assets/checkpoints/pi05_base/params"),
        num_train_steps=50_000,
        lr_schedule=_optimizer.CosineDecaySchedule(
            peak_lr=2.5e-5,
            decay_steps=50_000,
        ),
        freeze_filter=pi0_config.Pi0Config(pi05=True, action_horizon=32).get_freeze_filter(),
        ema_decay=None,
        assets_base_dir="./outputs/assets",
        checkpoint_base_dir="checkpoints",
        num_workers=8,
        batch_size=8 * 32,
    ),
    TrainConfig(
        name="pi05_b1k-pt50_cs32_bs64_lr2.5e-5_step50k",
        exp_name="openpi",
        project_name="B1K",
        model=pi0_config.Pi0Config(pi05=True, action_horizon=32),
        data=LeRobotB1KDataConfig(
            repo_id="behavior-1k/2025-challenge-demos",
            base_config=DataConfig(
                prompt_from_task=True,
                episodes_index=list(range(200)),
                behavior_dataset_root="../DATASETS/behavior/2025-challenge-demos",
                fine_grained_level=0,
            ),
        ),
        weight_loader=weight_loaders.CheckpointWeightLoader("gs://openpi-assets/checkpoints/pi05_base/params"),
        num_train_steps=50_000,
        lr_schedule=_optimizer.CosineDecaySchedule(
            peak_lr=2.5e-5,
            decay_steps=50_000,
        ),
        freeze_filter=pi0_config.Pi0Config(pi05=True, action_horizon=32).get_freeze_filter(),
        ema_decay=None,
        assets_base_dir="./outputs/assets",
        checkpoint_base_dir="checkpoints",
        num_workers=8,
        batch_size=8 * 32,
    ),
    TrainConfig(
        name="vlm2_b1k-pt50_cs32_bs64_lr2.5e-5_5ep",
        exp_name="openpi",
        project_name="B1K",
        model=VLM2VLAConfig(
            action_horizon=32,
            freeze_vggt_backbone=True,
            freeze_image_encoder=True,
        ),
        pytorch_model_name="vlm2",
        vlm2_num_frames=3,
        vlm2_geometry_dim=512,
        vlm2_view_dim=512,
        vlm2_working_memory_size=8,
        vlm2_episodic_memory_capacity=32,
        vlm2_episodic_similarity_threshold=0.7,
        vlm2_episodic_fusion_alpha=0.5,
        data=LeRobotB1KDataConfig(
            repo_id="behavior-1k/2025-challenge-demos",
            assets=AssetsConfig(
                assets_dir="checkpoints/openpi_comet/pi05-b1kpt50-cs32/assets",
                asset_id="behavior-1k/2025-challenge-demos",
            ),
            base_config=DataConfig(
                prompt_from_task=True,
                episodes_index=list(range(200)),
                behavior_dataset_root="/mnt/bn/robot-mllm-data-lf-3/mlx/users/chenjunting/data/2025-challenge-demos/",
                fine_grained_level=0,
            ),
        ),
        pytorch_weight_path="checkpoints/openpi_comet/pi05-b1kpt50-cs32",
        # num_train_steps=0 disables the step cap so num_train_epochs fully controls total steps
        num_train_steps=0,
        num_train_epochs=5,
        lr_schedule=_optimizer.CosineDecaySchedule(
            peak_lr=2.5e-5,
            # Estimated: 5 epochs × ~480k steps/epoch (pt50 dataset, batch_size=64, 8 GPUs).
            # Adjust if steps_per_epoch differs significantly after first run.
            decay_steps=2_400_000,
        ),
        freeze_filter=pi0_config.Pi0Config(pi05=True, action_horizon=32).get_freeze_filter(),
        ema_decay=None,
        assets_base_dir="./outputs/assets",
        checkpoint_base_dir="checkpoints",
        num_workers=16,
        batch_size_per_gpu=24,
    ),
    TrainConfig(
        name="pi05_b1k-pt50_cs32_bs64_lr2.5e-5_5ep",
        exp_name="openpi",
        project_name="B1K",
        model=pi0_config.Pi0Config(pi05=True, action_horizon=32),
        data=LeRobotB1KDataConfig(
            repo_id="behavior-1k/2025-challenge-demos",
            assets=AssetsConfig(
                assets_dir="checkpoints/openpi_comet/pi05-b1kpt50-cs32/assets",
                asset_id="behavior-1k/2025-challenge-demos",
            ),
            base_config=DataConfig(
                prompt_from_task=True,
                episodes_index=list(range(200)),
                behavior_dataset_root="/mnt/bn/robot-mllm-data-lf-3/mlx/users/chenjunting/data/2025-challenge-demos/",
                fine_grained_level=0,
            ),
        ),
        pytorch_weight_path="checkpoints/openpi_comet/pi05-b1kpt50-cs32",
        weight_loader=weight_loaders.CheckpointWeightLoader("sunshk/openpi_comet/pi05-b1kpt50-cs32"),
        # num_train_steps=0 disables the step cap so num_train_epochs fully controls total steps
        num_train_steps=0,
        num_train_epochs=5,
        lr_schedule=_optimizer.CosineDecaySchedule(
            peak_lr=2.5e-5,
            # Estimated: 5 epochs × ~180k steps/epoch (pt50 dataset, batch_size_per_gpu=64, 64 GPUs).
            # Adjust if steps_per_epoch differs significantly after first run.
            decay_steps=900_000,
        ),
        freeze_filter=pi0_config.Pi0Config(pi05=True, action_horizon=32).get_freeze_filter(),
        ema_decay=None,
        assets_base_dir="./outputs/assets",
        checkpoint_base_dir="checkpoints",
        num_workers=16,
        batch_size_per_gpu=64,
    ),
    TrainConfig(
        name="pi05-b1k-demo0_6-comet0_4-step20k",
        exp_name="openpi",
        project_name="B1K",
        model=pi0_config.Pi0Config(pi05=True, action_horizon=32),
        sample_weights=[0.6, 0.4],
        data=[
            LeRobotB1KDataConfig(
                repo_id="behavior-1k/2025-challenge-demos",
                base_config=DataConfig(
                    prompt_from_task=True,
                    behavior_dataset_root="../DATASETS/behavior/2025-challenge-demos",
                    fine_grained_level=0,
                ),
            ),
            LeRobotB1KDataConfig(
                repo_id="delinqu/comet-1.5k",
                base_config=DataConfig(
                    prompt_from_task=True,
                    behavior_dataset_root="../DATASETS/behavior/comet-1.5k",
                    fine_grained_level=0,
                ),
            ),
        ],
        weight_loader=weight_loaders.CheckpointWeightLoader("sunshk/openpi_comet/pi05-b1kpt50-cs32"),
        num_train_steps=20_000,
        lr_schedule=_optimizer.CosineDecaySchedule(
            peak_lr=1e-6,
            decay_steps=20_000,
        ),
        freeze_filter=pi0_config.Pi0Config(pi05=True, action_horizon=32).get_freeze_filter(),
        ema_decay=None,
        assets_base_dir="./outputs/assets",
        checkpoint_base_dir="checkpoints",
        num_workers=8,
        batch_size=8 * 32,
    ),
    TrainConfig(
        name="pi05_subtask_b1k-pt50_cs32_bs64_lr2.5e-5_5ep",  
        exp_name="openpi",
        project_name="B1K_wangzixuan",
        model=pi0_config.Pi05SubtaskConfig(action_horizon=32), 
        data=LeRobotB1KDataConfig(
            repo_id="behavior-1k/2025-challenge-demos",
            assets=AssetsConfig(
                assets_dir="checkpoints/openpi_comet/pi05-b1kpt50-cs32/assets",
                asset_id="behavior-1k/2025-challenge-demos",
            ),
            base_config=DataConfig(
                prompt_from_task=True,
                episodes_index=list(range(200)),
                behavior_dataset_root="/mnt/bn/robot-mllm-data-lf-3/mlx/users/chenjunting/data/2025-challenge-demos/",
                fine_grained_level=0,
            ),
            enable_subtask=True,  
        ),
        pytorch_weight_path="checkpoints/openpi_comet/pi05-b1kpt50-cs32",
        weight_loader=weight_loaders.CheckpointWeightLoader("sunshk/openpi_comet/pi05-b1kpt50-cs32"),
        num_train_steps=0,
        num_train_epochs=5,
        lr_schedule=_optimizer.CosineDecaySchedule(
            peak_lr=2.5e-5,
            decay_steps=900_000,
        ),
        freeze_filter=pi0_config.Pi05SubtaskConfig(action_horizon=32).get_freeze_filter(),
        ema_decay=None,
        assets_base_dir="./outputs/assets",
        checkpoint_base_dir="checkpoints",
        num_workers=16,
        batch_size_per_gpu=64,
    ),
]
